### ISSUE TITLE
broken configuration

### ISSUE THREAD

**Issue by danx0r** [codefaction/BusyBoxes#49]
yellow cell turns red
hash never seems to repeat

http://codefaction.github.io/BusyBoxes/?rule=rule3D3state&hash=HMAICM6

**Comment by gitorgstars** [comment]
even simpler and worse behaved: PGMBKAa

**Comment by gitorgstars** [comment]
vGAgU6

**Comment by danx0r** [comment]
2D has da bug ?dim=2&rule=rule2D3state&hash=vGAgR8
